config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get '/' => 'welcome#index'

  patch 'welcome/login', to: 'welcome#login'
  get 'welcome/login', to: 'welcome#login'
  get 'welcome/logout', to: 'welcome#logout'
  post 'welcome/logout', to: 'welcome#logout'

  resources :welcome, only: [:index, :create, :login, :logout]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :email,
      presence: true,
      uniqueness: {case_sensitive: false},
      uniqueness: true,
      format: { with: /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/ }

  validates :password,
      presence: true,
      length: { minimum: 8 },
      format: { with: /[A-Za-z0-9._]/ }

  def is_password?(password)
    BCrypt::Password.new(self.password_digest) == password
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
require 'geocoder'
require 'foursquare2'
require 'yelp'

class WelcomeController < ApplicationController
  include ApplicationHelper

  def index
    @user = User.new
    # client = Yelp::Client.new({ consumer_key: ENV['YELP_CONSUMER_KEY'],
    #                         consumer_secret: ENV['YELP_CONSUMER_SECRET'],
    #                         token: ENV['YELP_TOKEN'],
    #                         token_secret: ENV['YELP_TOKEN_SECRET']
    #                       })
    # params = { term: 'food', limit: 3, category_filter: 'discgolf' }

    # locale = { lang: 'fr' }

    # @response = client.search('San Francisco', params, locale)
    # # byebug
    # @response = @response.businesses[0].name
    @response = Geocoder.search("44.981667,-93.27833")
  end

  def create
    if params['password'] == params['password_confirmation']
      password = params['password']
      newUser = User.create(name: params['name'], email: params['email'], username: params['username'], password: params['password'], loginnum: 1)
      # newUser = User.create(user_params)
      if newUser
        # format.html { redirect_to @user, notice: 'You are now a member!' }
        # format.json { render :index, status: :created, location: @user }
        session[:user_id] = newUser.id
        # BuzzbitesMailer.buzzbites_welcome(params['email']).deliver_now
      else
        format.html { render :index }
        # format.json { render json: @user.errors, status: :unprocessable_entity }
        # render "Incorrect information"
      end
    end
    redirect_to(:back)
  end

  def login
    # Add one to each login a user has
    username = params['username']
    password = params['password']
    if  @user = User.find_by(username: username)
        # loginnum = @user.loginnum
      if @user.is_password?(password)
        session[:user_id] = @user.id
        # loginnum = loginnum + 1
        # @user.update(loginnum: loginnum.to_i)
        render :index
      else
        render text: "Invalid username/password."
      end
    end
  end

  def logout
      session.delete(:user_id)
      redirect_to "/"
  end

  # private
  #   def user_params
  #     params.require(:user).permit(:name, :email, :username, :password, loginnum: 1)
  #   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<% # //= depend_on_asset "bg_image2.jpg" %>
<% # //= depend_on_asset "bg_image3.jpg" %>

<!DOCTYPE html>
<html>
<head>
  <title>BuzzBites</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body class="orange lighten-5">
  <nav class="orange">
    <div class="navbar-wrapper container">
      <a href="#" class="brand-logo">BuzzBites</a>
      <ul class="right hide-on-small-only">

        <li id="signUpClick"><a>Sign Up</a></li>
        <% if session[:user_id] %><!--<li id="logoutClick"><a>Log Out</a></li>-->
        <%= link_to "Log Out", welcome_logout_path, method: "destroy" %>
        <% else %> <li id="loginClick"><a>Log In</a></li>
        <% end %>

      </ul>
      <!-- <div id="navlinkDivCenter"> -->
        <ul id="mobile-navlink" class="hide-on-med-and-up">
          <li id="signUpClick"><a>Sign Up</a></li>
          <% if session["id"] %><li id="logoutClick"><a>Log Out</a></li>
          <% else %> <li id="loginClick"><a>Log In</a></li>
          <% end %>
        </ul>
      <!-- </div> -->
    </div>
  </nav>
  <div class="parallax-container">
    <div class="parallax"><img src="/assets/bg_image2.jpg"></div>
  </div>

<%= yield %>

  <div class="parallax-container">
    <div class="parallax"><img src="/assets/bg_image3.jpg"></div>
  </div>
  <footer class="page-footer orange">
    <div class="container">
      <div class="row">
        <div class="col s6">
          <h5 class="white-text">About this site</h5>
          <p class="white-text">Want to eat what everyone else is eating? See what everyone else is posting? Let BuzzBites guide you to your next stop!</p>
        </div>
        <div class="col s3 offset-s3">
          <ul class="white-text">
            <li class="footer-list" id="scroll-top"><a>Top</a></li>
            <li class="footer-list" id="signUpClick"><a>Sign Up</a></li>
            <% if session[:user_id] %><!--<li id="logoutClick"><a>Log Out</a></li>-->
            <%= link_to "Log Out", welcome_logout_path, method: "destroy" %>
            <% else %> <li class="footer-list" id="loginClick"><a>Log In</a></li>
            <% end %>

            <!-- <li class="footer-list" id="loginClick">Log In</li> -->
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
        Copyright &copy; 2016 BuzzBites<br>
        Mekesia Brown | Reggie Kim | Victor Lin | David Patuwo
      </div>
    </div>
  </footer>

</body>
</html>

app/views/welcome/index.html.erb
<br/>
<div id="centerThis">
  <h5><em><b>Planning on eating somewhere else?</b></em></h5>
  <input placeholder="Enter the Zip Code!" type="text" name="zip-search" id="zip-search" /> <button class="btn waves-effect waves-light light blue" id="zip-search">Submit</button>
</div>
<br/>
<div id="centerThis">
  <h5 id="location-title"><em><b>Restaurants around you with Buzz</b></em></h5>
  <div>
    <%= @response %>
  </div>
  <ul id="displayData" class="collapsible" data-collapsible="accordion"></ul>
</div>
<br><br>
<div id="modal1" class="modal">
  <div class="modal-content" id="userSignUp">
    <br>
    <h4>Sign up with BuzzBites!</h4>
    <br>
    <%= form_tag("/welcome", method: "create") do %>
      <%= label_tag(:name, "Name:") %>
      <%= text_field_tag(:name, "", required: "required") %>
      <%= label_tag(:email, "Email:") %>
      <%= text_field_tag(:email, "", minlength: 8, required: "required") %>
      <%= label_tag(:username, "Username:") %>
      <%= text_field_tag(:username, "", required: "required") %>
      <%= label_tag(:password, "Password:") %>
      <%= password_field_tag(:password, "", minlength: 8, required: "required") %>
      <%= label_tag(:password_confirmation, "Confirm Password:") %>
      <%= password_field_tag(:password_confirmation, "", minlength: 8, required: "required") %>
      <%= submit_tag("Sign Up", class:"waves-effect waves-light btn light blue") %>
    <% end %>
  </div>
</div>

<div id="modal2" class="modal">
  <div class="modal-content" id="userLogin">
    <br>
    <h4>Welcome back! Please log in.</h4>
    <br>
    <%= form_tag(welcome_login_path, method: "patch") do %>
      <%= label_tag(:username, "Username:") %>
      <%= text_field_tag(:username, "", required: "required") %>
      <%= label_tag(:password, "Password:") %>
      <%= password_field_tag(:password, "", minlength: 8, required: "required") %>
      <%= submit_tag("Log in", class:"waves-effect waves-light btn light blue") %>
    <% end %>
  </div>
</div>

app/views/welcome/update.html.erb
<div id="userSignUp">
  <br><br>
  <%= form_for @user, method: 'post', url: {action: "create"} do |f| %>
    <% if @user.errors.any? %>
      <div>
        <h2>Your info is invalid</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.label(:name) %>
    <%= f.text_field :name %>
    <%= f.label(:email) %>
    <%= f.text_field :email %>
    <%= f.label(:username) %>
    <%= f.text_field :username %>
    <%= f.label(:password) %>
    <%= f.password_field :password %>
    <%= f.label(:password_confirmation) %>
    <%= f.password_field :password_confirmation %>
    <br><br>
    <%= f.submit "Sign up" %>
  <% end %>
</div>

<div id="userLogin">
  <br><br>
  <%= form_for @user, method: 'put', url: {action: "update"} do |f| %>
    <% if @user.errors.any? %>
      <div>
        <h2>Your info is invalid</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.label(:username) %>
    <%= f.text_field :username %>
    <%= f.label(:password) %>
    <%= f.password_field :password %>
    <br><br>
    <%= f.submit "Log in" %>
  <% end %>
</div>